### ISSUE TITLE
Aseprite Translation Manager

### ISSUE THREAD

**Issue by pixelartgirl** [realBoubli/Aseprite-French-Translation#1]
Hi to all translators of Aseprite!

I wrote a program "Aseprite Translation Manager" that can scan your translation INI file (any language) by comparing it to Aseprite’s en.ini file (in folder \data\strings).

Download the program and manual here to scan your own translation INI file in a very easy way and keep it up to date with latest Aseprite version.

https://github.com/pixelartgirl/Aseprite-Translation-Manager

PixelArtGirl

**Comment by realBoubli** [comment]
Could be interesting if we had the source? More on that, you just spawned here, your GitHub account is 3 days old, you "made" a Dutch translation (but one was already made more than a year ago) however your translation does not even exist. If we check your commits, you had one but inside nothing is translated. So yeah sorry but you're very suspicious so i won't launch you're exe. Meld do the job quite well for me, even if your tool looked useful.

Also, please don't use GitHub Issues to contact me or do your advertising.

**Comment by pixelartgirl** [comment]
Of course it's 3 days old, I joined 3 days ago. 

I'm still working on the translation and will be put online when finished...

There is no Dutch translation (not now, not a year ago): https://github.com/aseprite/languages

The exe is perfectly fine and very useful. You don't need any source to use it...

I suggest being a bit more polite. Your translation is not up to date, see screenshot of my tool.

![afbeelding](https://user-images.githubusercontent.com/105394924/168447546-282f6dc1-9522-4727-a13a-d58cdf70607e.png)

**Comment by realBoubli** [comment]
I'm sorry if your intention was only kindness and help (and it look like it). By reading you, I noticed that I confused Deutch and Dutch, that's my fault.

However, your exe can be perfectly fine and very useful, we are still on GitHub, and it's an _open source project_ hosting service.
More on that, the fact that your account is very new, and your translation repository with no link to download it, all of this was not inspiring me trust and reliability.
Yet I had some doubt, and thought about the fact that maybe it was just clumsiness. And apparently it was, and I'm sorry if I was rude, I didn't mean it.

Yup, my translation is not up to date, or is it? Officially 1.13 is still not out, so 1.12 is the last version. Anyway, I'm working on it to make it better, and also waiting the Aseprite 1.13 official release (or any big feature release) before pushing my changes.
I have already some pre-release available for the ones who wants the Tile/Tileset feature to be translated, and for the one who would want to use the new debugger, I doubt that it will annoy them.

Good luck with your translation, it's a lot of work.
PS: I love Belgium and I'm reaaaally sorry to have mistaken it with Germany.
Peace

**Comment by pixelartgirl** [comment]
The official 1.3 will have the same strings as the 1.3 beta (which already has 14 releases!) so you can use my tool already (if you want). They don't change translation strings when going from beta to official (just only the code of the program itself).
Maybe a very tiny amount of strings are changed, but that's why I made my tool...

Yes, I just wanted to help in order to give you an easy way to do this. Otherwise you need programs to compare 2 INI files like WinMerge etc. which will take much more time. With my tool it's compared in some seconds.

My Dutch translation will be uploaded later, I'm checking it with my own tool. I had typos in string names etc and also forgot things. The tool was made because I was getting crazy to find typos or missing things XD
